In [172]:
import numpy as np

In [187]:
A = np.array(
    [[2, 6, 4],
     [1, 4, 3],
     [-2, -3, 0]]
)

In [188]:
def LU_decompose(A):
    L = []
    U = []
    for i in range(len(A)):
        temp_col = A[i].copy()
        temp_row = np.zeros(A.shape[1])
        factor = 0
        fac_row = 0
        for j in range(A.shape[1]):
            if A[i][j] != 0:
                factor = A[i][j]
                fac_row = j
                break
        for j in range(i, len(A)):
            temp_row[j] = A[j][fac_row]/factor
            A[j] = A[j] - temp_row[j]*temp_col
        U.append(temp_col)
        L.append(temp_row)
    U = np.array(U).transpose()
    L = np.array(L)
    return L, U

def solve_LU(L, U, y):
    x = np.zeros(len(L))
    tx = np.zeros(len(L))
    LT = L.transpose()
    UT = U.transpose()
    for i in range(L.shape[1]):
        temp = y[i]
        for j in range(len(L)):
            if j != i:
                temp -= tx[j]*LT[i][j]
        tx[i] = temp/(LT[i][i])
    for i in reversed(range(U.shape[1])):
        temp = tx[i]
        for j in range(len(U)):
            if j != i:
                temp -= x[j]*UT[i][j]
        x[i] = temp/(UT[i][i])
    return x

In [190]:
L, U = LU_decompose(A.copy().transpose())
print(L)
print(U)

[[1. 3. 2.]
 [0. 1. 1.]
 [0. 0. 1.]]
[[ 2  0  0]
 [ 1  1  0]
 [-2  3  1]]


In [176]:
y = np.array([1, 5, 5])
x = solve_LU(L, U, y)
print(x)

[ 2. -1.  1.]
